import {
  Activity,
  AlertTriangle,
  Archive,
  BarChart3,
  Boxes,
  Calculator,
  Clock,
  Cloud,
  Database,
  Download,
  FileText,
  Gauge,
  History,
  Info,
  LayoutGrid,
  Layers,
  ListChecks,
  Package,
  Scissors,
  Settings,
  Shield,
  SlidersHorizontal,
  Sparkles,
  Upload,
  Users,
  Warehouse,
  Wrench,
  type LucideIcon,
} from "lucide-react";

/** Single mapping from semantic names to concrete icon components so screens
 *  reference an icon by role rather than importing lucide symbols directly. */
export const icons = {
  dashboard: LayoutGrid,
  calculator: Calculator,
  cut: Scissors,
  history: History,
  warehouse: Warehouse,
  reports: FileText,
  settings: Settings,
  material: Layers,
  jumbo: Package,
  boxes: Boxes,
  archive: Archive,
  analytics: BarChart3,
  gauge: Gauge,
  clock: Clock,
  quick: Sparkles,
  security: Shield,
  database: Database,
  diagnostics: Activity,
  cloud: Cloud,
  maintenance: Wrench,
  users: Users,
  error: AlertTriangle,
  download: Download,
  upload: Upload,
  about: Info,
  logs: ListChecks,
  tune: SlidersHorizontal,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;
export type { LucideIcon };
