/** Centralized user-facing strings. Keeping copy in one place keeps tone
 *  consistent and makes future localization a single-file change. */
export const strings = {
  appName: "Производство",
  tabs: {
    dashboard: "Обзор",
    calculator: "Расчёт",
    materials: "Материалы",
    warehouse: "Склад",
    history: "История",
    reports: "Отчёты",
    settings: "Настройки",
  },
  analytics: {
    title: "Отчёты",
    subtitle: "Центр производственных отчётов",
    empty: "Отчёты не найдены",
  },
  dashboard: {
    title: "Обзор",
    subtitle: "Производственная панель",
  },
  calculator: {
    title: "Расчёт нарезки",
    materialSection: "Параметры материала",
    rollSection: "Размер готового рулона",
    results: "Результаты",
  },
  production: {
    title: "Производство",
    orderInfo: "Информация о заказе",
    jumbo: "Джамб",
    selectJumbo: "Выбрать Джамб",
    usedJumbo: "Используемый Джамб",
    changeJumbo: "Сменить Джамб",
    availableTitle: "Доступные Джамбы",
    noJumbos: "Нет доступных Джамбов",
    noJumbosHint: "Оприходуйте партию сырья на складе, чтобы выбрать Джамб.",
    params: "Параметры рулона",
    results: "Результаты",
    execute: "Выполнить заказ и списать",
    addWaste: "Добавить брак",
    wastePending: "Брак и технологические остатки фиксируются при закрытии Джамба.",
    firstUseNotice: "Джамб переведён в работу — начато использование.",
    writeOffNotice:
      "Остаток материала менее 300 метров. Джамб завершён. Для следующего заказа необходимо выбрать новый Джамб.",
    successNotice: "Заказ выполнен, остаток Джамба обновлён.",
    fillOrder: "Заполните информацию о заказе (заказчик, номер заказа, оператор).",
  },
  history: {
    title: "История",
    empty: "Пока нет сохранённых расчётов",
    emptyHint: "Выполните расчёт и сохраните его, чтобы он появился здесь",
  },
  materials: {
    title: "Материалы",
    empty: "Справочник материалов пуст",
    emptyHint: "Добавьте первый материал, чтобы оприходовать сырьё",
  },
  warehouse: {
    title: "Склад Джамбов",
    empty: "На складе пока нет Джамбов",
    emptyHint: "Оприходуйте партию сырья, чтобы Джамбы появились здесь",
    needMaterial: "Сначала добавьте материал в справочнике",
  },
  receipt: {
    title: "Поступление сырья",
  },
  jumbo: {
    title: "Карточка Джамба",
    timeline: "Журнал операций",
  },
  archive: {
    title: "Архив",
    empty: "Архив пуст",
    emptyHint:
      "Закрытые и списанные Джамбы автоматически переносятся сюда с полной статистикой.",
  },
  settings: {
    title: "Настройки",
    company: "Название предприятия",
    operator: "Оператор",
    email: "Email",
    autoSend: "Автоматическая отправка отчётов",
    darkTheme: "Тёмная тема",
    version: "Версия приложения",
  },
  admin: {
    general: "Основные",
    generalHint: "Предприятие, оператор, оформление",
    production: "Производство",
    productionHint: "Пороги, станки, форматы",
    email: "Рассылка отчётов",
    emailHint: "Получатели и расписание",
    security: "Безопасность",
    securityHint: "PIN, автоблокировка, подтверждения",
    backup: "Резервное копирование",
    backupHint: "Создание, восстановление, экспорт",
    maintenance: "Обслуживание базы",
    maintenanceHint: "Целостность, связи, кэш",
    diagnostics: "Диагностика",
    diagnosticsHint: "Состояние базы и версии",
    logs: "Журналы",
    logsHint: "Ошибки и аудит действий",
    about: "О приложении",
    aboutHint: "Версия, хранилище, планы",
    groupApp: "Приложение",
    groupData: "Данные и обслуживание",
    groupSystem: "Система",
    errorsTab: "Ошибки",
    auditTab: "Аудит",
    noErrors: "Ошибок не зафиксировано",
    noAudit: "Записей аудита нет",
    clear: "Очистить",
    createBackup: "Создать копию",
    downloadBackup: "Скачать JSON",
    importBackup: "Импорт из JSON",
    restore: "Восстановить",
    checkIntegrity: "Проверить целостность",
    checkRelations: "Проверить связи",
    optimize: "Оптимизировать",
    rebuild: "Перестроить индексы",
    clearCache: "Очистить кэш",
    integrityOk: "Проблем не обнаружено",
    storageProviders: "Хранилище",
    exportFormats: "Форматы экспорта",
    importSources: "Источники импорта",
  },
  intelligence: {
    notificationsTitle: "Центр уведомлений",
    notificationsSubtitle: "Автоматические предупреждения",
    noNotifications: "Активных уведомлений нет",
    decisionsTitle: "Центр решений",
    decisionsSubtitle: "Прогнозы, качество, рекомендации",
    forecast: "Прогнозирование",
    quality: "Контроль качества",
    recommendations: "Рекомендации",
    noRecommendations: "Рекомендаций нет — показатели в норме",
    searchTitle: "Глобальный поиск",
    searchSubtitle: "Джамбы, заказы, материалы, архив",
    searchPlaceholder: "Поиск по всей системе…",
    searchEmpty: "Введите запрос для поиска",
    searchNoResults: "Ничего не найдено",
    settingsHistoryTitle: "История изменений",
    settingsHistorySubtitle: "Журнал изменений настроек",
    noSettingsHistory: "Изменений настроек не зафиксировано",
    integrationsTitle: "Интеграции",
    integrationsSubtitle: "ERP, 1С, SAP, REST, CSV",
    markSeen: "Просмотрено",
    markDone: "Выполнено",
    anomaly: "Аномалия",
  },
} as const;
